const kluby_nazwy=[
    "1. SKS Ściechów (Ściechów)",
    "10 Olsztyn (Olsztyn)",
    "10-KA Sulmierzyce (Sulmierzyce)",
    "7,62 Trzcianka (Trzcianka)",
    "9 MM Białystok (Białystok)",
    "9 MM Koszalin (Koszalin)",
    "AB Piotrków Trybunalski (Piotrków Trybunalski)",
    "AEROKLUB Poznań (Poznań)",
    "AGAT Złotoryja (Złotoryja)",
    "AGATSU Czeladź (Czeldź)",
    "AKMS Opole (Opole)",
    "ALFA Będzin (Będzin)",
    "ALFA Kętrzyn (Kętrzyn)",
    "AMARANT Poznań (Poznań)",
    "AMATOR Wrocław (Wrocław)",
    "AQUILA Nowy Dwór Mazowiecki (Nowy Dwór Mazowiecki)",
    "ARDEA Gdańsk (Gdańsk)",
    "ARES Gorzów Wlkp. (Gorzow Wlkp)",
    "ARIZONA Lublin (Lublin)",
    "ARSENAŁ BEZPIECZEŃSTWA Kołacinek (Dmosin)",
    "ARSENAŁ Kraków (Kraków)",
    "ARSENAŁ Zakroczym (Zakroczym)",
    "AT Gdańsk (Gdańsk)",
    "ATLAS Warszawa (Warszawa)",
    "AWANGARDA Zamość (Zamość)",
    "AZS Częstochowa (Częstochowa)",
    "AZSPŚ Kielce (Kielce)",
    "B7 Warszawa (Warszawa)",
    "BARYS Ząbkowice Śląskie (Ząbkowice Śląskie)",
    "BASTION Łódź (Łódź)",
    "BASTION Żabice (Żabice)",
    "BASZTA Gryfice (Gryfice)",
    "BASZTA Łęczyca (Łęczyca)",
    "BAZUKA Piątnica (Piątnica)",
    "BEE SHOT Ligota Zamecka (Ligota Zamecka)",
    "BELLONA Kalisz (Kalisz)",
    "BEZPIECZNA LUBELSZCZYZNA Lublin (Lublin)",
    "BIELIK Dźwierzuty (Dźwierzuty)",
    "BK Bytom (Bytom)",
    "BK Jelenia Góra (Jelenia Góra)",
    "BK Kraków (Kraków)",
    "BK Łódź (Łódź)",
    "BK Rawicz (Rawicz)",
    "BK Rybnik (Rybnik)",
    "BK Tarnów (Tarnów)",
    "BK Wrocław (Wrocław)",
    "BK Wronki (Wronki)",
    "BKS LOK Bydgoszcz (Bydgoszcz)",
    "BLASTER Bielsko-Biała (Bielsko-Biała)",
    "BŁYSK Odolanów (Odolanów)",
    "BOCK Rawicz (Rawicz)",
    "BRASS Gorzów Wlkp. (Gorzów Wlkp.)",
    "BRYGADA Poznań (Poznań)",
    "BS Głogówek (Głogówek)",
    "BS Mikołów (Mikołów)",
    "BUNKIER Warszawa (Warszawa)",
    "BUNKIER Zduńska Wola (Zduńska Wola)",
    "BURSZTYN Kalisz (Kalisz)",
    "C.S RANCZO GŁUPONIE (GLUPONIE)",
    "C22 Łochów (Łochów)",
    "C4 GUNS Łódź (Łódź)",
    "CAMP X Karpicko (Karpicko)",
    "CARPATIA Rzeszów (Rzeszów)",
    "CBK Cieszyn (Cieszyn)",
    "CEL Góra (Góra)",
    "CEL Grójec (Grójec)",
    "CEL Kędzierzyn-Koźle (Kędzierzyn-Koźle)",
    "CHEMIK Lublin (Lublin)",
    "CLUB 308 Białystok (Białystok)",
    "COLT Łódź (Łódź)",
    "COMBAT Kalisz (Kalisz)",
    "COMBAT SHOOTING Knyszyn (Knyszyn)",
    "COMMANDO Luboń (Poznań)",
    "CON-TRA Gorzów Wlkp. (Gorzów Wielkopolski)",
    "COVER Warszawa (Warszawa)",
    "CSS Częstochowa (Częstochowa)",
    "CSS Nałęcz (Czarnków)",
    "CWS Słupsk (Słupsk)",
    "CZ5 Lublewo Gdańskie (Lublewo Gdańskie)",
    "CZAK Świdnica (Świdnica)",
    "CZARNY LOTOS Złotniki (ZŁOTNIKI)",
    "CZART Sucha Beskidzka (Sucha Beskidzka)",
    "DEFA Oleśnica (Oleśnica)",
    "DEFENDU Poznań (Poznań)",
    "DELFIN Biedrusko (Biedrusko)",
    "DELFIN Tarnów (Tarnów)",
    "DELTA Bytom (Bytom)",
    "DELTA Dobiegniew (Dobiegniew)",
    "DIANA Poznań (Poznań)",
    "DO CELU Leszno (Leszno)",
    "DO CELU Przemyśl (Przemyśl)",
    "DRAGON Chełm (Chełm)",
    "DRAGON Siedlce (Siedlce)",
    "DRAGON Zdrójno (Zdrójno)",
    "DRUH Janów Lubelski (Janów Lubelski)",
    "DWÓR GRUNWALDZKI Poznań (Poznań)",
    "DYWIZJON Jonnik (TUCHOWICZ)",
    "DYWIZJON Poznań (Poznań)",
    "DZIESIĄTKA Kartuzy (Kartuzy)",
    "DZIESIĄTKA Lublin (Lublin)",
    "DZIESIĄTKA Łódź (Łódź)",
    "ERMADOR Bielsko-Biała (Bielsko-Biała)",
    "ESHOT Wałbrzych (Wałbrzych)",
    "EXCALIBUR Zgierz (Zgierz)",
    "EXPERT Jaworzno (Jaworzno)",
    "EZS Elbląg (Elbląg)",
    "FENIKS Twardogóra (Twardogóra)",
    "FENIKS Węgrów (Węgrów)",
    "FLOR-AMATOR Świętochłowice (Świętochłowice)",
    "FLOTA Elbląg (Elbląg)",
    "FLOTA Gdynia (Gdynia)",
    "FORMOZA Widzino (Widzino)",
    "FORT Słupca (Słupca)",
    "FORT Zgorzelec (JERZMANKI)",
    "FUN GUN Świdnik (Świdnik)",
    "GALICJA Sanok (Brzozów)",
    "GARDA Gdynia (Gdynia)",
    "GARDA Ostróda (Ostróda)",
    "GASTON Redło (Redło)",
    "GENTLEMAN Warszawa (Kozery)",
    "GILZA Pleszew (Pleszew)",
    "GIWERA Rybnik (Rybnik)",
    "GKS FLOTA (Gdynia)",
    "GKS Gliwice (Gliwice)",
    "GLAUBERYT Żabice (Żabice)",
    "GRAJCAR Police (Police)",
    "GROM Sławno (Sławno)",
    "GROM Tarnobrzeg (Tarnobrzeg)",
    "GROT Białystok (Białystok)",
    "GROT Płock (Płock)",
    "GROT Puck (Puck)",
    "GRUNWALD Poznań (Poznań)",
    "GRYF Grodzisk Wlkp. (Grodzisk Wielkopolski)",
    "GRYF SŁUPSKI Słupsk (Słupsk)",
    "GSC Chełm Śląski (Chełm Śląski)",
    "GUARDIAN Biała Podlaska (Biała Podlaska)",
    "GUARDIANS Kalisz (Kalisz)",
    "GUN CLUB Bielsko-Biała (Bielsko-Biała)",
    "GUN STORM Toruń (TORUŃ)",
    "GUNSLINGER Dobre Miasto (Dobre Miasto)",
    "GWARD Kwidzyn (Kwidzyn)",
    "GWARDIA 1924 Sosnowiec (Sosnowiec)",
    "GWARDIA Olsztyn (Olsztyn)",
    "GWARDIA Zielona Góra (Zielona Góra)",
    "HAJDUKI Chorzów (Chorzów)",
    "HALINKA ARMS Jawiszowice (Jawiszowice)",
    "HAMER Kozienice (Kozienice)",
    "HART Twardogóra (Twardogóra)",
    "HETMAN Nysa (Nysa)",
    "HONOR Wolsztyn (Wolsztyn)",
    "HTS Kraków (Kraków)",
    "HUBERTUS Gutkowo (Olsztyn)",
    "HUSAR Komarówka Podl. (Komarówka Podlaska)",
    "HUSAR Rzeszów (Rzeszów)",
    "HUSARIA Krosno (Krosno)",
    "HUSARZ Tułowice (Tułowice)",
    "HUSARZ Wrocław (Wrocław)",
    "HUZAR Oleśnica (Oleśnica)",
    "HUZAR Opole (Opole)",
    "IC Piła (Piła)",
    "IGLICA Warszawa (Warszawa)",
    "IGNIS Wrocław (Wrocław)",
    "IGWA Wawrzeńczyce (Wawrzeńczyce)",
    "IMPULS Szczecinek (Szczecinek)",
    "IRON TEDDY Bukowa (Bukowa)",
    "JASTRZĄB Elizówka (Elizówka)",
    "JASTRZĄB Swarzędz (Swarzędz)",
    "JASZCZUR Gdynia (Gdynia)",
    "JEDENASTKA Witaszyce (Witaszyce)",
    "JRS Kowalewko (Kowalewko)",
    "JS 4051 Włocławek (Włocławek)",
    "JTS Jaworzno (Jaworzno)",
    "JURA Kochcice (Kochcice)",
    "K-15 Halickie (Halickie)",
    "K.S. \"Młody Strzelec\" (Bochnia)",
    "KABAR Łódź (Łódź)",
    "KADET Gorzów Wlkp. (Gorzów Wielkopolski)",
    "KALIBER 30 Dawidy Bankowe (Dawidy Bankowe)",
    "KALIBER 7,62 Skwierzyna (Skwierzyna)",
    "KALIBER Białystok (Białystok)",
    "KALIBER Koszalin (Koszalin)",
    "KALIBER Małaszewicze (Małaszewicze)",
    "KALIBER Mława (Mława)",
    "KALIBER Oława (Oława)",
    "KALIBER Pszów (Pszów)",
    "KALIBER Zawiercie (Zawiercie)",
    "KALIBER.22 Czaplinek (Czaplinek)",
    "KALIBER.44 Rogów Opolski (Rogów Opolski)",
    "KARKONOSZE Miłków (Miłków)",
    "KASZTELAN Rzeszów (Rzeszów)",
    "KBS Gdynia (Gdynia)",
    "KBS Margonin (Margonin)",
    "KBS Opalenica (Opalenica)",
    "KBS Pszczyna (Pszczyna)",
    "KBS Starogard Gdański (Starogard Gdański)",
    "KBS Swarzędz (Swarzędz)",
    "KBS Śmigiel (Śmigiel)",
    "KBS Śrem (Śrem)",
    "KBS Tarnowo Podgórne (Tarnowo Podgórne)",
    "KBS Tarnowskie Góry (Tarnowskie Góry)",
    "KBS Wejherowo (Wejherowo)",
    "KBS Wolsztyn (Wolsztyn)",
    "KBS Zbąszynek (Zbąszynek)",
    "KBS Żory (Żory)",
    "KBSK Kalisz (Kalisz)",
    "KKSS SCHRON 85 (Konin)",
    "KOBE Pawłów (Pawłów)",
    "KOBUDO Opole (Opole)",
    "KOCHAMBROŃ.PL Kraków (Kraków)",
    "KOLIMATOR Łódź (Łódź)",
    "KOMANDOR Katowice (Katowice)",
    "KOMUNALNI Ozorków (Ozorków)",
    "KOPERNIK Gdańsk (GDAŃSK)",
    "KORMORAN Olsztyn (Olsztyn)",
    "KOS Bugaj (BUGAJ)",
    "KRECHOWIAK Augustów (Gabowe Grądy)",
    "KROKUS Nowy Sącz (Nowy Sącz)",
    "KROWODRZA Kraków (Kraków)",
    "KRUK Łask (Łask)",
    "KRYZA Gdynia (Gdynia)",
    "KS EMJOT (CHRZÓW)",
    "KS Gdańsk (Gdańsk)",
    "KS INVICTUS  Łęg Przedmiejski (Lelis)",
    "KS Kołobrzeg (Kołobrzeg)",
    "KS LOK Chojnice (Chojnice)",
    "KS LOK Dąbrowa Górnicza (Dąbrowa Górnicza)",
    "KS LOK Myszków (Myszków)",
    "KS TATRY (Brzegi)",
    "KS Ustroń (Ustroń)",
    "KS ZO LOK Kraków (Kraków)",
    "KSB Paczółtowice (Paczółtowice)",
    "KSI Gdynia (Gdynia)",
    "KSISTART Szczecin (Szczecin)",
    "KSK Kostrzyn (Kostrzyn nad Odrą)",
    "KSK TROFEUM MALBORK (Nowa Wieś Malborska)",
    "KSO Świdnica (Świdnica)",
    "KSS Ciechanów (Ciechanów)",
    "KTS Kraków (Kraków)",
    "KURTA Bobolice (Bobolice)",
    "KVG Paczółtowice (Paczółtowice)",
    "KŻR LOK Gdańsk (Gdańsk)",
    "KŻR LOK Opole (Opole)",
    "KŻR Warka (Warka)",
    "LAS Hanna (Adampol)",
    "LBK Luboń (Luboń)",
    "LEGIA Warszawa (Warszawa)",
    "LEGION SILESIA Ruda Śląska (Ruda Śląska)",
    "LEGION Stalowa Wola (Stalowa Wola)",
    "LEGION Stargard (Stargard)",
    "LEGION Tarnów (Tarnów)",
    "LEGION WSCHODNI Turośń Kościelna (Turośń Kościelna)",
    "LESNA Leszno (Leszno)",
    "LEWART Olempin (Markuszów)",
    "LIDER-AMICUS Lębork (Lębork)",
    "LOK Białogard (Białogard)",
    "LOKOWIEC Biała Podlaska (Biała Podlaska)",
    "LOKUS Olkusz (Olkusz)",
    "LOTNIK Rosnowo (Rosnowo)",
    "LTS Legionowo (Legionowo)",
    "LTS Leszno (Leszno)",
    "LUPUS Zgorzelec (Dłużyna Dolna)",
    "MAGNUM Błaszki (Błaszki)",
    "MAGNUM Chełm (Chełm)",
    "MAGNUM Poznań (Poznań)",
    "MARGOLIN Kalisz (Kalisz)",
    "MARKSMAN Szkocja (Szkocja)",
    "MECHANIK Tomaszów Mazowiecki (Tomaszów Mazowiecki)",
    "MGP Kaliska (Kaliska)",
    "MIEDZIANI Lubin (Lubin)",
    "MKS LOK Racibórz (Racibórz)",
    "MKS Rybnik (Rybnik)",
    "MSS Słomniki (Słomniki)",
    "MTS Sulejówek (Sulejówek)",
    "MUSZKIET Konin (Konin)",
    "MUSZKIET Słubice (Słubice)",
    "MUSZKIET Wieleń (Wieleń)",
    "MZPB Kraków (Kraków)",
    "NA CELOWNIKU Wilków (Wilków)",
    "NADIR Jędrzejów (Jędrzejów)",
    "NADNARWIANKA Pułtusk (Pułtusk)",
    "NEPTUN Kosakowo (Kosakowo)",
    "NIECZAJNA Złotniki (Złotniki)",
    "NOXODA Chrzanów (Chrzanów)",
    "NSHM Dęblin (Dęblin)",
    "NSS Czarnków (Czarnków)",
    "NTS Warszawa (Warszawa)",
    "OBIECTUM Kędzierzyn Koźle (Kędzierzyn Koźle)",
    "OBROŃCA Troszyn (Troszyn)",
    "OGNIOMISTRZ Mielec (Mielec)",
    "OLENDER Wielka Nieszawka (Wielka Nieszawka)",
    "OMEGA Gdańsk (Gdańsk)",
    "ONE MAN ARMY Łódź (Łódź)",
    "OPW Lesk (Olecko)",
    "ORĘŻ Ełk (Ełk)",
    "ORLIK Lublin (Lublin)",
    "ORNECKIE SMOKI Orneta (Orneta)",
    "ORZEŁ Gołdap (Gołdap)",
    "ORZEŁ Kutno (Kutno)",
    "PARASOL Węgorzewo (Węgorzewo)",
    "PARASOL Wschowa (Wschowa)",
    "PASJONACI Łagów (Łagów)",
    "PASJONAT Opole (Opole)",
    "PATRON Grajewo (Grajewo)",
    "PATRON Krasnystaw (Krasnystaw)",
    "PERKUN Kamienna Góra (Kamienna Góra)",
    "PERKUN Miszewko (Miszewko)",
    "PERUN Luboń (Luboń)",
    "PESTKA JABŁONNA (Jabłonna)",
    "PETARDA Kraków (Kraków)",
    "PETRUCI Toruń (Toruń)",
    "PGKM Wołomin (Wołomin)",
    "PIAST Bieruń (Bieruń)",
    "PIAST Opole (Opole)",
    "PIONIER Gubin (Gubin)",
    "PKS Mielno (Mielno)",
    "PKS Piła (Piła)",
    "PNGS Nowogard (Sieciechowo)",
    "PODLASIE Białystok (Białystok)",
    "POGRANICZE Bogatynia (Bogatynia)",
    "POLE WIDZENIA Bydgoszcz (BYDGOSZCZ)",
    "POLIGON DRAWSKI Oleszno (Oleszno)",
    "POLONIA Jelenia Góra (Jelenia Góra)",
    "PRECYZJA Kraków (Kraków)",
    "PRETOR Lubiszyn (Lubiszyn)",
    "PROELIA Warszawa (Warszawa)",
    "PROMIEŃ Bochnia (Bochnia)",
    "PROPORZEC Opalenica (Opalenica)",
    "PRZESMYK Suwałki (Suwałki)",
    "PSSW Łódź (Śniatowa)",
    "PTS Płock (Płock)",
    "PUCHACZ Piotrków Trybunalski (Piotrków Trybunalski)",
    "PWKS Swaróg (Pieszyce)",
    "RAGUN Radom (Radom)",
    "RANKALIBER Zagorzyce (Zagorzyce)",
    "RATEL Ełk (Ełk)",
    "RCS Panaszew (Panaszew)",
    "REGALICA Gryfino (Gryfino)",
    "RELOAD Gromadka (Gromadka)",
    "RENEGACI Bytkowo (Bytkowo)",
    "RP Aleksandrów Łódzki (Aleksandrów Łódzki)",
    "RYKOSZET Radomsko (Radomsko)",
    "SAGGITA Świdnica (Świdnica)",
    "SAGITTARIUS Gogolin (Gogolin)",
    "SAGITTARIUS Piątnica (Piątnica Poduchowna)",
    "SALWA Szczerców (Szczerców)",
    "SALWA Wołomin (Wołomin)",
    "SAS Augustów (Augustów)",
    "SCHRON Lublin (Lublin)",
    "SENIOR Gdańsk (Gdańsk)",
    "SFORA Czaplino (Czaplino)",
    "SHADOW Mosina (Mosina)",
    "SHOOTER Lublin (Lublin)",
    "SHOOTING-ACADEMY Łódź (Łódź)",
    "SIGMA SHOOTING Łódź (Łódź)",
    "SILESIA GORILLAS Katowice (Katowice)",
    "SILESIA GUNS Gierałtowice (Gierałtowice)",
    "SILESIA-SUPERIOR Knurów (Knurów)",
    "SILVER TARGET Kraków (Kraków)",
    "SKAUT Bielsko-Biała (Bielsko-Biała)",
    "SKORPION Juszki (Juszki)",
    "SKORPION Mielec (Mielec)",
    "SKORPION Polkowice (Polkowice)",
    "SKSS Skierniewice (Skierniewice)",
    "SMKS Kęty (Kęty)",
    "SMOLANY Radoryż (Radoryż Smolany)",
    "SNAJPER Garwolin (Garwolin)",
    "SNAJPER Lublin (Lublin)",
    "SNAJPER Lubrza (Lubrza)",
    "SNAJPER Mrągowo (Mrągowo)",
    "SNAJPER Ostrowo (Mrocza)",
    "SNAJPER Płońsk (Płońsk)",
    "SNAJPER Poznań (Poznań)",
    "SNAJPER Włosty Olszanka (Włosty Olszanka)",
    "SNAJPER Wójcin (Wójcin)",
    "SNAJPER Wrocław (Wrocław)",
    "SOKÓŁ Czechowice-Dziedzice (Czechowice-Dziedzice)",
    "SOKÓŁ Jedlicze (Jedlicze)",
    "SOKÓŁ Kazimierz Biskupi (Kazimierz Biskupi)",
    "SOKÓŁ Lublin (Lublin)",
    "SOKÓŁ Mirsk (Mirsk)",
    "SOKÓŁ Parczew (Parczew)",
    "SOKÓŁ Ryn (Ryn)",
    "SOKÓŁ Sokołów Podl. (Sokołów Podlaski)",
    "SOKÓŁ Szerominek (Szerominek)",
    "SOKÓŁ Zduńska Wola (Zduńska Wola)",
    "SOLNY GARNIZON Bochnia (Bochnia)",
    "SOM I Gliwice (Gliwice)",
    "SPARTA Kędzierzyn-Koźle (Kedzierzyn-Koźle)",
    "SPARTAKUS Lublin (Lublin)",
    "SPECTRUM Żółwin (Żółwin)",
    "SPOŁEM Łódź (Łódź)",
    "SQUAD Kraków (Kraków)",
    "SS KBS Borek Wlkp. (Borek Wielkopolski)",
    "SS KOBUDO OPOLE (Opole)",
    "SSK Pszczyna (Pszczyna)",
    "SSS Dziemiany (Dziemiany)",
    "SSS Wałbrzych (Wałbrzych)",
    "START Gorzów Wlkp. (Gorzów Wielkopolski)",
    "START OLSZTYNEK (OLSZTYNEK)",
    "STEN Wąwolnica (Wąwolnica)",
    "STONE RANGE Dmosin (Koziołki)",
    "STRAŻAK Golub Dobrzyń (Golub-Dobrzyń)",
    "STRZAŁ Prudnik (Prudnik)",
    "STRZELCY Bytów (Rzepnica)",
    "STRZELCY MORSCY Gdynia (Gdynia)",
    "STRZELCY Sosnowiec (Sosnowiec)",
    "STRZELCY Wrocław (Brzeg Dolny)",
    "STRZELEC Jedlicze (Jedlicze)",
    "STRZELEC Jelenia Góra (Jelenia Góra)",
    "STRZELEC Łódź (Łódź)",
    "STRZELEC Myślenice (Myślenice)",
    "STRZELEC Sawin (Sawin)",
    "STRZELEC Szczecin (Szczecin)",
    "STRZELEC Zielona Góra (Zielona Góra)",
    "STRZELEC Żyrardów (Żyrardów)",
    "STRZELKA Głogów Młp. (Zabajka)",
    "STRZELMISTRZ Łódź (Łódź)",
    "STS Szczecin (Szczecin)",
    "SUDECKA WATAHA Kłodzko (Kłodzko)",
    "SWKS Warka (Warka)",
    "SZANIEC Prażmów (Prażmów)",
    "SZAROTKA Nowy Targ (Nowy Targ)",
    "SZWADRON Białystok (Białystok)",
    "ŚLĄSK Wrocław (Wrocław)",
    "ŚTS Tychy (Tychy)",
    "ŚWIT Starachowice (Starachowice)",
    "TACTICAL CORE Gorzów (Gorzów)",
    "TARCZA Gdynia (Gdynia)",
    "TARCZA Goleniów (Goleniów)",
    "TARCZA Ozorków (Mikołajew)",
    "TARCZA Piła (Piła)",
    "TARCZA Poznań (Borówiec)",
    "TARCZA Starogard Gd. (Starogard Gdański)",
    "TARCZA Szamotuły (Szamotuły)",
    "TARGET Suwałki (Suwałki)",
    "TE Inowrocław (Inowrocław)",
    "TECHNIK Zamość (Zamość)",
    "TEMIDA Zabrze (Zabrze)",
    "TERYTORIALNI Kraków (Kraków)",
    "TF88 Gdynia (Gdynia)",
    "TIG Iława (Iława)",
    "TKS LOK Tarnów (Tarnów)",
    "TOP-GUN Aleksandrów Łódzki (Aleksandrów Łódzki)",
    "TRIGGER POINT Książenice (MIŃSK MAZOWIECKI)",
    "TROFEUM Malbork (Nowa Wieś Malborska)",
    "TS 44 Kraków (Kraków)",
    "TSP Postomino (Postomino)",
    "TUR Leszno (Leszno)",
    "TWIERDZA Przemyśl (Przemyśl)",
    "TWIERDZA Zamość (Zamość)",
    "U27 Ołtarzew (Ołtarzew)",
    "UNIVERSAL Wrocław (Wrocław)",
    "UR Jawor (Jawor)",
    "VALKIRIA Leszno (Leszno)",
    "VIP Będzin (Będzin)",
    "VIS Gostyń (Gostyń)",
    "VIS Kwidzyn (Kwidzyn)",
    "VIS Lipno (Lipno)",
    "VIS Łomża (Łomża)",
    "VIS Mielec (Mielec)",
    "VIS Międzyrzec Podlaski (Międzyrzec Podlaski)",
    "VIS Nisko (Nisko)",
    "VIS Radom (Radom)",
    "VIS Tuchola (Tuchola)",
    "VIS Wrocław (Wrocław)",
    "VIS Zamość (Zamość)",
    "WALKIRIA Świebodzice (Świebodzice)",
    "WALTHER Gdynia (Gdynia)",
    "WANAD Olsztyn (Olsztyn)",
    "WARMIA I MAZURY Olsztyn (Olsztyn)",
    "WARTA Uniejów (Uniejów)",
    "WAWEL Kraków (Kraków)",
    "WETERAN Opole (Opole)",
    "WIARUS Oborniki (Oborniki)",
    "WIARUS Płock (Płock)",
    "WIG Gniezno (Gniezno)",
    "WIGRY Suwałki (Suwałki)",
    "WILK Olecko (Olecko)",
    "WILK Trzebnica (Trzebnica)",
    "WISKI 66 Wiski (Tuczna)",
    "WISŁA Kraków (Kraków)",
    "WKSS Poznań (Poznań)",
    "WLKS GRUNWALD Poznań (Poznań)",
    "WOLF PACK Szamotuły (Szamotuły)",
    "WROTA 44 Konstantynów Łódzki (Konstantynów Łódzki)",
    "WSCC WARSZAWA (Warszawa)",
    "WSS Jonkowo (Jonkowo)",
    "WSS Wrocław (Wrocław)",
    "ZAĆMA Tuchola (Tuchola)",
    "ZAMEK Łańcut (Łańcut)",
    "ZAWISZA Bydgoszcz (Bydgoszcz)",
    "ZBROJNI Gdańsk (Gdańsk)",
    "ZBROJOWNIA Modlin (Nowy Dwór Mazowiecki)",
    "ZBROJOWNIA Suchy Las (Suchy Las)",
    "ZIEMIA CHEŁMIŃSKA Toruń (Toruń)",
    "ZKS Warszawa (Warszawa)",
    "ZŁOTY RÓG Zielona Góra (Zielona Góra)",
    "ZSD Kraków (Kraków)",
    "ŻUŁAWY Braniewo (Braniewo)",
    "ŻYWIEC Moszczanica (Żywiec)"
];
