// Skroty klubow z wczesniejszych list wtyczki (2023, 2024). Konwerter CSV rozpoznaje dzieki nim
// kluby z formularzy utworzonych starszymi wersjami, nawet jesli zniknely z rejestru PZSS.
const kluby_historyczne=[
    "1. SKS Ściechów",
    "10 Olsztyn",
    "10-KA Radomsko",
    "10-KA Sulmierzyce",
    "7,62 Trzcianka",
    "9 MM Białystok",
    "9 MM Koszalin",
    "AB Piotrków Trybunalski",
    "AEROKLUB Poznań",
    "AGAT Złotoryja",
    "AGATSU Będzin",
    "AKMS Opole",
    "ALFA Będzin",
    "ALFA Kętrzyn",
    "ALFA Siemianowice Śląskie",
    "ALU-PRO Opole",
    "AMARANT Poznań",
    "AMATOR Wrocław",
    "AQUILA Nowy Dwór Mazowiecki",
    "ARDEA Gdańsk",
    "ARMA-IPA Bielsko-Biała",
    "ARSENAŁ Kraków",
    "ASO Głogów",
    "AT Gdańsk",
    "ATLAS Warszawa",
    "AWANGARDA Zamość",
    "AZS Częstochowa",
    "AZS Częstochowa (nie)",
    "AZSPŚ Kielce",
    "B7 Warszawa",
    "BARYS Ząbkowice Śląskie",
    "BASTION Kęty",
    "BASTION Łódź",
    "BASTION Żabice",
    "BASZTA Gryfice",
    "BASZTA Łęczyca",
    "BAZUKA Piątnica",
    "BELLONA Grodzisk Mazowiecki",
    "BELLONA Kalisz",
    "BEZPIECZNA LUBELSZCZYZNA Lublin",
    "BIELIK Dźwierzuty",
    "BK Bytom",
    "BK Jelenia Góra",
    "BK Kraków",
    "BK Łódź",
    "BK Rawicz",
    "BK Rybnik",
    "BK Szczecinek",
    "BK Tarnów",
    "BK Wrocław",
    "BK Wronki",
    "BKG Bytom",
    "BKS LOK Bydgoszcz",
    "BLASTER Bielsko-Biała",
    "BŁYSK Odolanów",
    "BOCK Rawicz",
    "BRASS Gorzów Wlkp.",
    "BRYGADA Poznań",
    "BS Głogówek",
    "BS Mikołów",
    "BUNKIER Zduńska Wola",
    "BURSZTYN Kalisz",
    "C22 Łochów",
    "C4 GUNS Łódź",
    "CAMP X Karpicko",
    "CBK Cieszyn",
    "CEL Góra",
    "CEL Grójec",
    "CEL Kędzierzyn-Koźle",
    "CHEMIK Lublin",
    "CLUB 308 Białystok",
    "COLT Łódź",
    "COMBAT Kalisz",
    "COMBAT SHOOTING Knyszyn",
    "COMMANDO Luboń",
    "CON-TRA Gorzów Wlkp.",
    "COVER Warszawa",
    "CSS Częstochowa",
    "CWS Słupsk",
    "CZ5 Gdańsk",
    "CZ5 Lublewo Gdańskie",
    "CZAJKA Zakopane",
    "CZAK Świdnica",
    "CZART Sucha Beskidzka",
    "DE LA SALLE Gdańsk",
    "DEFENDU Poznań",
    "DELFIN Biedrusko",
    "DELFIN Tarnów",
    "DELTA Bytom",
    "DELTA Dobiegniew",
    "DIANA Poznań",
    "DO CELU Przemyśl",
    "DRAGON Chełm",
    "DRAGON Siedlce",
    "DRAGON Zdrójno",
    "DRUH Janów Lubelski",
    "DWÓR GRUNWALDZKI Poznań",
    "Dywizjon Jonnik",
    "DYWIZJON Poznań",
    "DZIESIĄTKA Kartuzy",
    "DZIESIĄTKA Kartuzy (nie)",
    "DZIESIĄTKA Lublin",
    "DZIESIĄTKA Łódź",
    "ELITA Lublin",
    "ELITA Szczecin",
    "ERMADOR Bielsko-Biała",
    "ESASC Włościejewki",
    "ESHOT Wałbrzych",
    "EXCALIBUR Zgierz",
    "EXPERT Jaworzno",
    "EZS Elbląg",
    "FENIKS Twardogóra",
    "FENIKS Węgrów",
    "FLOR-AMATOR Świętochłowice",
    "FLOTA Elbląg",
    "FLOTA Gdynia",
    "FORMOZA Widzino",
    "FORT Słupca",
    "FORT Zgorzelec",
    "FUN GUN Świdnik",
    "GALICJA Rzeszów",
    "GARDA Gdynia",
    "GARDA Ostróda",
    "GASTON Redło",
    "GATLING Połczyn Zdrój",
    "GENTLEMAN GUN CLUB Warszawa",
    "GENTLEMAN Warszawa",
    "GILZA Pleszew",
    "GIWERA Rybnik",
    "GKS FLOTA Gdynia",
    "GKS Gliwice",
    "GLAUBERYT Żabice",
    "GRAJCAR Police",
    "GRANICA Bolesławiec",
    "GROM Sławno",
    "GROM Tarnobrzeg",
    "GROT Białystok",
    "GROT Mikołajewo",
    "GROT Płock",
    "GROT Puck",
    "GRUNWALD Poznań",
    "Grupa Wawelberg Ruda Śląska",
    "GRYF Grodzisk Wlkp.",
    "GRYF SŁUPSKI Słupsk",
    "GRYF Szczecin",
    "GSC Chełm Śląski",
    "GUARDIAN Biała Podlaska",
    "GUN CLUB Bielsko-Biała",
    "GUN STORM Toruń",
    "GUNSLINGER Dobre Miasto",
    "GWARD Kwidzyn",
    "GWARDIA 1924 Sosnowiec",
    "GWARDIA Olsztyn",
    "GWARDIA Zielona Góra",
    "HAJDUKI Chorzów",
    "HALINKA ARMS Jawiszowice",
    "HAMER Kozienice",
    "HART Twardogóra",
    "HETMAN Nysa",
    "HTS Kraków",
    "HUBERTUS Gutkowo",
    "HUBERTUS Olsztyn",
    "HUSAR Komarówka Podl.",
    "HUSAR Rzeszów",
    "HUSARIA Krosno",
    "HUSARZ Tułowice",
    "HUSARZ Wrocław",
    "HUZAR Oleśnica",
    "HUZAR Opole",
    "IC Piła",
    "IGLICA Bełchatów",
    "IGLICA Warszawa",
    "IGNIS Wrocław",
    "IMPULS Szczecinek",
    "IRON TEDDY Bukowa",
    "JASTRZĄB Elizówka",
    "JASTRZĄB Swarzędz",
    "JASZCZUR Gdynia",
    "JRS Kowalewko",
    "JTS Jaworzno",
    "JURA Kochcice",
    "K-15 Halickie",
    "KABAR Łódź",
    "KADET Gorzów Wlkp.",
    "KALIBER 30 Dawidy Bankowe",
    "KALIBER 7,62 Skwierzyna",
    "KALIBER Białystok",
    "KALIBER Koszalin",
    "KALIBER Małaszewicze",
    "KALIBER Mława",
    "KALIBER Oława",
    "KALIBER Zawiercie",
    "KALIBER.22 Czaplinek",
    "KALIBER.44 Rogów Opolski",
    "KASZTELAN Rzeszów",
    "KBS Gdynia",
    "KBS Koźmin Wlkp.",
    "KBS Margonin",
    "KBS Opalenica",
    "KBS Pszczyna",
    "KBS Raszków",
    "KBS Starograd Gdański",
    "KBS Swarzędz",
    "KBS Śmigiel",
    "KBS Śrem",
    "KBS Tarnowo Podgórne",
    "KBS Tarnowskie Góry",
    "KBS Wolsztyn",
    "KBS Zbąszynek",
    "KBS Żory",
    "KBSK Kalisz",
    "KOBE Jelcz Laskowice",
    "KOBUDO Opole",
    "KOCHAMBROŃ.PL Kraków",
    "KOLIMATOR Łódź",
    "KOMANDOR Katowice",
    "KOMUNALNI Ozorków",
    "KORMORAN Olsztyn",
    "KRECHOWIAK Augustów",
    "KROKUS Nowy Sącz",
    "KROWODRZA Kraków",
    "KRUK Łask",
    "KRYZA Gdynia",
    "KS BUNKIER Zduńska Wola",
    "KS CARPATIA",
    "KS Gdańsk",
    "KS Kołobrzeg",
    "KS LOK Chojnice",
    "KS LOK Dąbrowa Górnicza",
    "KS LOK Myszków",
    "KS MARGOLIN Kalisz",
    "KS USTROŃ",
    "KS ZO LOK Kraków",
    "KSB Paczółtowice",
    "KSI Gdynia",
    "KSK Pasjonaci Łagów",
    "KSO Świdnica",
    "KSS Ciechanów",
    "KSS Schron",
    "KTS Kraków",
    "KURTA Bobolice",
    "KVG Paczółtowice",
    "KŻR LOK Gdańsk",
    "KŻR LOK Leszno",
    "KŻR LOK Opole",
    "KŻR LOK Starogard Gdański",
    "KŻR Warka",
    "KŻR-LOK Gdańsk",
    "KŻR-LOK Starogard Gdański",
    "LAS Hanna",
    "LBK Luboń",
    "LEGIA Warszawa",
    "LEGION SILESIA Ruda Śląska",
    "LEGION Stalowa Wola",
    "LEGION Stargard",
    "LEGION Tarnów",
    "LEGION WSCHODNI Turośń Kościelna",
    "LESNA Leszno",
    "LIDER-AMICUS Lębork",
    "LOK Białogard",
    "LOKOWIEC Biała Podlaska",
    "LOKUS Olkusz",
    "LOTNIK Rosnowo",
    "LTS Legionowo",
    "LTS Leszno",
    "LUPUS Zgorzelec",
    "MAGNUM Błaszki",
    "MAGNUM Chełm",
    "MAGNUM Poznań",
    "MARKSMAN Szkocja",
    "MGP Kaliska",
    "MIEDZIANI Lubin",
    "MKS IGWA",
    "MKS LOK Racibórz",
    "MKS Rybnik",
    "MKS-LOK Racibórz",
    "MOST Gdynia",
    "MSS Słomniki",
    "MTS Sulejówek",
    "MUSZKIET Konin",
    "MUSZKIET Słubice",
    "MUSZKIET Wieleń",
    "MZPB Kraków",
    "NADIR Jędrzejów",
    "NADNARWIANKA Pułtusk",
    "NEPTUN Kosakowo",
    "NIECZAJNA Złotniki",
    "NSHM Dęblin",
    "NSS Czarnków",
    "NSS Lubasz",
    "NTS Warszawa",
    "OBROŃCA Troszyn",
    "OBUCHOWO Nowy Dwór",
    "OGNIOMISTRZ Mielec",
    "OLENDER Wielka Nieszawka",
    "OMEGA Gdańsk",
    "ONE MAN ARMY Łódź",
    "ORĘŻ Ełk",
    "ORLIK Lublin",
    "ORNECKIE SMOKI Orneta",
    "ORZEŁ Elbląg",
    "ORZEŁ Kutno",
    "OSiR Koluszki",
    "PARASOL Warszawa",
    "PARASOL Węgorzewo",
    "PARASOL Wschowa",
    "PASJONAT Opole",
    "PATRON Grajewo",
    "PATRON Krasnystaw",
    "PERKUN Kamienna Góra",
    "PERKUN Miszewko",
    "PERUN Luboń",
    "PETARDA Kraków",
    "PETRUCI Toruń",
    "PGKM Radzymin",
    "PIAST Bieruń",
    "PIAST Opole",
    "PIONIER Gubin",
    "PKS Mielno",
    "PKS Piła",
    "PNGS Nowogard",
    "PODKARPACIE Jedlicze",
    "PODLASIE Białystok",
    "POGRANICZE Bogatynia",
    "POLIGON DRAWSKI Oleszno",
    "POLONIA Jelenia Góra",
    "PRECYZJA Kraków",
    "PRETOR Lubiszyn",
    "PROELIA Warszawa",
    "PROMIEŃ Bochnia",
    "PROPORZEC Opalenica",
    "PRZESMYK Suwałki",
    "PSSW Łódź",
    "PUCHACZ Piotrków Trybunalski",
    "RAGUN Radom",
    "RANKALIBER Zagorzyce",
    "RATEL Ełk",
    "RCS Panaszew",
    "REGALICA Gryfino",
    "RELOAD Gromadka",
    "RP Aleksandrów Łódzki",
    "RYKOSZET Radomsko",
    "SAGGITA Świdnica",
    "SAGITTARIUS Gogolin",
    "SAGITTARIUS Piątnica",
    "SALWA Szczerców",
    "SALWA Wołomin",
    "SAS Augustów",
    "SENIOR Gdańsk",
    "SHADOW Mosina",
    "SHOOTER Lublin",
    "SHOOTING-ACADEMY Łódź",
    "SIGMA SHOOTING Łódź",
    "SILESIA GORILLAS Katowice",
    "SILESIA GUNS Gierałtowice",
    "SILESIA-SUPERIOR Knurów",
    "SILEZJAN Wrocław",
    "SILVER TARGET Kraków",
    "SKAUT Bielsko-Biała",
    "SKORPION Juszki",
    "SKORPION Polkowice",
    "SKSS Rogów",
    "SKSS Skierniewice",
    "SMKS Kęty",
    "SNAJPER Garwolin",
    "SNAJPER Lublin",
    "SNAJPER Lubrza",
    "SNAJPER Mrągowo",
    "SNAJPER Płońsk",
    "SNAJPER Poznań",
    "SNAJPER Włosty Olszanka",
    "SNAJPER Wójcin",
    "SNAJPER Wrocław",
    "SOKÓŁ Czechowice-Dziedzice",
    "SOKÓŁ Jedlicze",
    "SOKÓŁ Kazimierz Biskupi",
    "SOKÓŁ Lublin",
    "SOKÓŁ Mirsk",
    "SOKÓŁ Parczew",
    "SOKÓŁ Płońsk",
    "SOKÓŁ Ryn",
    "SOKÓŁ Sokołów Podl.",
    "SOKÓŁ Szerominek",
    "SOKÓŁ Zduńska Wola",
    "SOLNY GARNIZON Bochnia",
    "SOM I Gliwice",
    "SPARTA Kędzierzyn-Koźle",
    "SPARTAKUS Lublin",
    "SPECTRUM Żółwin",
    "SPOŁEM Łódź",
    "SQUAD Kraków",
    "SS KBS Borek Wlkp.",
    "SS KOBUDO OPOLE",
    "SS Wiski",
    "SSS Wałbrzych",
    "START Gorzów Wlkp.",
    "START Szczecin",
    "STEN Wąwolnica",
    "STONE RANGE Dmosin",
    "STRAŻAK Golub Dobrzyń",
    "STRZAŁ Prudnik",
    "STRZELCY Bytów",
    "STRZELCY MORSCY Gdynia",
    "STRZELCY Wrocław",
    "STRZELEC Jedlicze",
    "STRZELEC Jelenia Góra",
    "STRZELEC Łódź",
    "STRZELEC Sawin",
    "STRZELEC Szczecin",
    "STRZELEC Zielona Góra",
    "STRZELEC Żyrardów",
    "STRZELKA Głogów Młp.",
    "STRZELMISTRZ Łódź",
    "STS Szczecin",
    "SUDECKA WATAHA Kłodzko",
    "SWKS Warka",
    "SZANIEC Prażmów",
    "SZAROTKA Nowy Targ",
    "SZWADRON Białystok",
    "ŚLĄSK Wrocław",
    "ŚTS Tychy",
    "ŚWIT Starachowice",
    "TARCZA 96 Poznań",
    "TARCZA Gdynia",
    "TARCZA Goleniów",
    "TARCZA Ozorków",
    "TARCZA Piła",
    "TARCZA Poznań",
    "TARCZA Starogard Gd.",
    "TARCZA Szamotuły",
    "TARGET Suwałki",
    "TE Inowrocław",
    "TECHNIK Zamość",
    "TEMIDA Zabrze",
    "TERYTORIALNI Kraków",
    "TF88 Gdynia",
    "TIG Iława",
    "TKS LOK Tarnów",
    "TMA 1993 Kalisz",
    "TOP-GUN Aleksandrów Łódzki",
    "TROFEUM Malbork",
    "TS 44 Kraków",
    "TSBK Kraków",
    "TWIERDZA Przemyśl",
    "TWIERDZA Zamość",
    "U27 Ołtarzew",
    "UKS ZSM Kielce",
    "ULKS Jedlińsk",
    "UNIVERSAL Wrocław",
    "UR Jawor",
    "VALKIRIA Leszno",
    "VARMINT Szczecin",
    "VICTORIA Wieruszów",
    "VIP Będzin",
    "VIP Olsztyn",
    "VIS Gostyń",
    "VIS Kwidzyn",
    "VIS Lipno",
    "VIS Łomża",
    "VIS Mielec",
    "VIS Międzyrzec Podlaski",
    "VIS Nisko",
    "VIS Radom",
    "VIS Tuchola",
    "VIS Wrocław",
    "VIS Zamość",
    "WALKIRIA Świebodzice",
    "WALTHER Gdynia",
    "WANAD Olsztyn",
    "WARMIA I MAZURY Olsztyn",
    "WARTA Uniejów",
    "WAWEL Kraków",
    "WETERAN Opole",
    "WIARUS Oborniki",
    "WIARUS Płock",
    "WIGRY Suwałki",
    "WILK Olecko",
    "WILK Sokołowice",
    "WISŁA Kraków",
    "WKSS Poznań",
    "WLKS GRUNWALD Poznań",
    "WOLF PACK Szamotuły",
    "WROTA 44 Konstantynów Łódzki",
    "WSCC LOK WARSZAWA",
    "WSS Jonkowo",
    "WSS Wrocław",
    "ZAĆMA Tuchola",
    "ZAMEK Łańcut",
    "ZARABIE Myślenice",
    "ZAWISZA Bydgoszcz",
    "ZBROJNI Gdańsk",
    "Zbrojownia Modlin",
    "ZBROJOWNIA Modlin",
    "ZBROJOWNIA MODLIN Nowy Dwór Mazowiecki",
    "ZBROJOWNIA Suchy Las",
    "ZIEMIA CHEŁMIŃSKA Toruń",
    "ZJEDNOCZENI STRZELCY Szczecin",
    "ZKS Warszawa",
    "ZSD Kraków",
    "ŻUŁAWY Braniewo",
    "ŻYWIEC Moszczanica"
];
